-- AlterTable
ALTER TABLE "Venta" ADD COLUMN IF NOT EXISTS "metodoPago" VARCHAR(50);
ALTER TABLE "Venta" ADD COLUMN IF NOT EXISTS "comprobante" VARCHAR(100);
ALTER TABLE "Venta" ADD COLUMN IF NOT EXISTS "comprobanteKey" VARCHAR(255);
ALTER TABLE "Venta" ADD COLUMN IF NOT EXISTS "comprobanteMime" VARCHAR(100);
ALTER TABLE "Venta" ADD COLUMN IF NOT EXISTS "comprobanteNombre" VARCHAR(255);
ALTER TABLE "Venta" ADD COLUMN IF NOT EXISTS "medico" VARCHAR(120);
ALTER TABLE "Venta" ADD COLUMN IF NOT EXISTS "modulo" VARCHAR(60);
ALTER TABLE "Venta" ADD COLUMN IF NOT EXISTS "notas" TEXT;
